### ISSUE TITLE
modpack crashes

### ISSUE THREAD

**Issue by alpharulesirulee** [alpharulesirulee/MODPACK-CRASHES#1]

**Comment by alpharulesirulee** [comment]
Starting up SoundSystem...
[13:38:19] [Thread-10/INFO] [Mantle-STDERR/]: [paulscode.sound.SoundSystemLogger]: Initializing LWJGL OpenAL
[13:38:19] [Thread-10/INFO] [Mantle-STDERR/]: [paulscode.sound.SoundSystemLogger]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:38:21] [Thread-10/INFO] [Mantle-STDERR/]: [paulscode.sound.SoundSystemLogger]: OpenAL initialized.
[13:38:21] [Sound Library Loader/INFO] [Mantle-STDERR/]: [paulscode.sound.SoundSystemLogger]: 
[13:38:39] [Client thread/INFO] [Mantle-STDERR/]: [net.minecraft.client.Minecraft]: ---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/3/15 1:38 PM
Description: Registering texture

java.lang.OutOfMemoryError: Registering texture
    at java.util.zip.Inflater.inflateBytes(Native Method)
    at java.util.zip.Inflater.inflate(Unknown Source)
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at javax.imageio.stream.MemoryCache.loadFromStream(Unknown Source)
    at javax.imageio.stream.MemoryCacheImageInputStream.read(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readFully(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readFully(Unknown Source)
    at com.sun.imageio.plugins.gif.GIFImageReaderSpi.canDecodeInput(Unknown Source)
    at javax.imageio.ImageIO$CanDecodeInputFilter.filter(Unknown Source)
    at javax.imageio.spi.FilterIterator.advance(Unknown Source)
    at javax.imageio.spi.FilterIterator.<init>(Unknown Source)
    at javax.imageio.spi.ServiceRegistry.getServiceProviders(Unknown Source)
    at javax.imageio.ImageIO.getImageReaders(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:127)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.zip.Inflater.inflateBytes(Native Method)
    at java.util.zip.Inflater.inflate(Unknown Source)
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at javax.imageio.stream.MemoryCache.loadFromStream(Unknown Source)
    at javax.imageio.stream.MemoryCacheImageInputStream.read(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readFully(Unknown Source)
    at javax.imageio.stream.ImageInputStreamImpl.readFully(Unknown Source)
    at com.sun.imageio.plugins.gif.GIFImageReaderSpi.canDecodeInput(Unknown Source)
    at javax.imageio.ImageIO$CanDecodeInputFilter.filter(Unknown Source)
    at javax.imageio.spi.FilterIterator.advance(Unknown Source)
    at javax.imageio.spi.FilterIterator.<init>(Unknown Source)
    at javax.imageio.spi.ServiceRegistry.getServiceProviders(Unknown Source)
    at javax.imageio.ImageIO.getImageReaders(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:127)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/atlas/blocks.png
    Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61)
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 296803864 bytes (283 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 4 total; -Xms256M -Xmx1024M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 133 mods loaded, 133 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.9} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.62} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.9} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.9.jar) Unloaded->Constructed->Pre-initialized
    AromaBackup{0.0.0.4} [AromaBackup](AromaBackup-1.7.10-0.0.0.4.jar) Unloaded->Constructed->Pre-initialized
    BetterTitleScreen{1.7.10-1.1} [Better Title Screen](BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.8.1} [BiblioCraft](BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsBoP{1.8} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.8].jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.648-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.648-experimental.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{@VERSION@} [BuildCraft](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsForestry{1.6} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.6].jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc10} [Big Reactors](BigReactors-0.4.0rc10.jar) Unloaded->Constructed->Pre-initialized
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.0a} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0a%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized
    Botania{r1.2-129} [Botania](Botania r1.2-129.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{@VERSION@} [BC Builders](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{@VERSION@} [BC Transport](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{@VERSION@} [BC Silicon](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{@VERSION@} [BC Factory](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{@VERSION@} [BC Energy](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.2.8} [Carpenter's Blocks](Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.13} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.13-universal.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    CompactSolars{4.4.37.314} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.37.314-universal.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.1.5.248} [Ender IO](EnderIO-1.7.10-2.1.5.248.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    factorization{1.7.10-0.8.88.1} [Factorization](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    EnetBridge{1.4} [EnetBridge](enetbridge-1.4.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.310} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.310-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized
    factorization.misc{1.7.10-0.8.88.1} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized
    funkylocomotion{1.0} [Funky Locomotion](funky-locomotion-1.7.10-beta-2.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl{2.0.0b} [Nuclear Control 2](IC2NuclearControl-2.0.0b.jar) Unloaded->Constructed->Pre-initialized
    inpure|core{1.7.10R1.0.0B1} [INpureCore](INpureCore-[1.7.10]1.0.0B1-1.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-155-5dbbb14} [Inventory Tweaks](InventoryTweaks-1.59-dev-155.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.4a} [Waila](Waila-1.5.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    journeymap{5.0.0RC1} [JourneyMap](JourneyMap5.0.0RC1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.1} [The Twilight Forest](twilightforest-1.7.10-2.3.1.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineMenu{1.1.8} [MineMenu](MineMenu-1.7.10-1.1.8.B40-universal.jar) Unloaded->Constructed->Pre-initialized
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9B.jar) Unloaded->Constructed->Pre-initialized
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughCodecs{0.3} [NotEnoughCodecs](NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore](OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheral{0.2.0} [OpenPeripheralAddons](OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-433.jar) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.2.14-29} [PneumaticCraft](PneumaticCraft-1.7.10-1.2.14-29-universal.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized
    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized
    StevesFactoryManager{A92} [Steve's Factory Manager](StevesFactoryManagerA92.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed->Pre-initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-19.jar) Unloaded->Constructed->Pre-initialized
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized
    TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Core{1.4.1.6} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.6-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Addons{1.4.1.6} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.6-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Logic{1.4.1.6} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.6-universal.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.310} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.310-universal.jar) Unloaded->Constructed->Pre-initialized
    aobd{2.2.5} [Another One Bites The Dust](AOBD-2.2.5.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.310} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.310-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.17.10.2963, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

[13:38:39] [Client thread/INFO] [Mantle-STDERR/]: [net.minecraft.client.Minecraft]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Isaiah\Downloads\direwolf20_17\minecraft\crash-reports\crash-2015-01-03_13.38.39-client.txt
